# Generated by Django 5.2.11 on 2026-02-14 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True, verbose_name='Key')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('price', models.FloatField(verbose_name='Price')),
                ('max_tickets', models.IntegerField(verbose_name='Maximum Tickets')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iftf_duoverkoop.association')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Modified')),
                ('created_by', models.ForeignKey(help_text='User who created this purchase', on_delete=django.db.models.deletion.PROTECT, related_name='purchases_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this purchase', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases_modified', to=settings.AUTH_USER_MODEL)),
                ('ticket1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket1', to='iftf_duoverkoop.performance')),
                ('ticket2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket2', to='iftf_duoverkoop.performance')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted')], help_text='Type of action performed', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action occurred')),
                ('changes', models.JSONField(blank=True, help_text='JSON object containing the changes made (for UPDATE actions)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who made the change', null=True)),
                ('purchase', models.ForeignKey(help_text='The purchase this log entry refers to', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='iftf_duoverkoop.purchase')),
                ('user', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='iftf_duover_timesta_482972_idx'), models.Index(fields=['purchase', '-timestamp'], name='iftf_duover_purchas_8439a9_idx'), models.Index(fields=['user', '-timestamp'], name='iftf_duover_user_id_9815f1_idx')],
            },
        ),
    ]
