# Generated by Django 5.2.11 on 2026-02-14 23:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iftf_duoverkoop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='verification_code',
            field=models.CharField(db_index=True, default='null-null-null', help_text="Unique three-word code for purchase verification (e.g., 'happy-tree-button')", max_length=100, unique=True, verbose_name='Verification Code'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['verification_code'], name='iftf_duover_verific_1d4a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['-date'], name='iftf_duover_date_81ef19_idx'),
        ),
    ]
