# Generated by Django 5.2.11 on 2026-03-07 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iftf_duoverkoop', '0002_purchase_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-date'], 'permissions': [('export_data', 'Can export purchase data to CSV'), ('verify_purchase', 'Can look up purchases by verification code')]},
        ),
    ]
