# Generated by Django 3.2.8 on 2022-11-12 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iftf_duoverkoop', '0003_auto_20221112_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performance',
            name='name',
            field=models.CharField(default='NONE', editable=False, max_length=128, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performance',
            name='price',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performance',
            name='tickets',
            field=models.IntegerField(default=0, verbose_name='Tickets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='name',
            field=models.CharField(default='NONE', editable=False, max_length=128, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
