# Generated by Django 5.2.11 on 2026-03-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iftf_duoverkoop', '0004_loginauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseauditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True),
        ),
    ]
