# Generated by Django 3.2.8 on 2022-11-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iftf_duoverkoop', '0004_auto_20221112_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='tickets',
        ),
        migrations.AddField(
            model_name='performance',
            name='max_tickets',
            field=models.IntegerField(default=30, verbose_name='Maximum Tickets'),
            preserve_default=False,
        ),
    ]
