# Generated by Django 3.2.8 on 2022-11-12 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iftf_duoverkoop', '0005_auto_20221112_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iftf_duoverkoop.association'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='key',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='ticket1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket1', to='iftf_duoverkoop.performance'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='ticket2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket2', to='iftf_duoverkoop.performance'),
        ),
    ]
