# Generated by Django 5.2.11 on 2026-03-07 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iftf_duoverkoop', '0005_alter_purchaseauditlog_ip_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationRepProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association', models.ForeignKey(help_text='The association this representative belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='rep_profiles', to='iftf_duoverkoop.association')),
                ('user', models.OneToOneField(help_text='The association representative user account', on_delete=django.db.models.deletion.CASCADE, related_name='association_rep_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Association Rep Profile',
                'verbose_name_plural': 'Association Rep Profiles',
            },
        ),
    ]
