# Generated by Django 5.2.11 on 2026-03-07 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iftf_duoverkoop', '0006_associationrepprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='purchaseauditlog',
            name='iftf_duover_purchas_8439a9_idx',
        ),
        migrations.AddField(
            model_name='purchaseauditlog',
            name='purchase_id_snapshot',
            field=models.IntegerField(blank=True, db_index=True, help_text='Numeric purchase ID captured at log time; survives purchase deletion', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseauditlog',
            name='changes',
            field=models.JSONField(blank=True, help_text="Self-contained snapshot of the purchase state at the time of the action. CREATE: {'state': {...full purchase fields...}}. UPDATE: {'before': {...}, 'after': {...}, 'diff': {...changed fields only...}}. DELETE: {'final_state': {...full purchase fields...}}.", null=True),
        ),
        migrations.AlterField(
            model_name='purchaseauditlog',
            name='purchase',
            field=models.ForeignKey(blank=True, help_text='The purchase this log entry refers to (NULL once the purchase is deleted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='iftf_duoverkoop.purchase'),
        ),
        migrations.AddIndex(
            model_name='purchaseauditlog',
            index=models.Index(fields=['purchase_id_snapshot', '-timestamp'], name='iftf_duover_purchas_d8f9c4_idx'),
        ),
    ]
