# Generated by Django 5.2.11 on 2026-03-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iftf_duoverkoop', '0007_remove_purchaseauditlog_iftf_duover_purchas_8439a9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='email_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('NOT_SENT', 'Not sent (disabled)')], db_index=True, default='PENDING', help_text='Tracks whether the confirmation email was successfully delivered.', max_length=10, verbose_name='Email Status'),
        ),
    ]
