# Generated by Django 5.2.11 on 2026-02-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iftf_duoverkoop', '0007_purchase_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
