# Generated by Django 5.2.11 on 2026-03-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iftf_duoverkoop', '0008_add_purchase_email_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='discounted_price',
            field=models.FloatField(blank=True, help_text='Reduced price for buyers with a culture card (cultuurkaart). Leave blank if no discount applies.', null=True, verbose_name='Discounted Price (culture card)'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='has_culture_card',
            field=models.BooleanField(default=False, help_text='Whether the buyer presented a culture card (cultuurkaart) for a discount.', verbose_name='Has culture card'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='student_id',
            field=models.CharField(blank=True, default='', help_text='Student ID (e.g. r0000000) required when a culture-card discount is applied.', max_length=20, verbose_name='Student ID'),
        ),
    ]
