# Generated by Django 4.1.2 on 2026-03-18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iftf_duoverkoop', '0009_add_discount_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('BACKUP', 'Backup'), ('RESTORE', 'Restore')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('backup_filename', models.CharField(blank=True, default='', help_text='Filename relative to media/backups.', max_length=255)),
                ('original_upload_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('file_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('is_pre_restore_backup', models.BooleanField(default=False, help_text='True for automatic safety backup created before a restore job.')),
                ('notes', models.TextField(blank=True, default='')),
                ('output_log', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(help_text='User that triggered this database operation.', on_delete=django.db.models.deletion.PROTECT, related_name='database_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('manage_database_backups', 'Can run database backup and restore operations')],
                'indexes': [models.Index(fields=['operation_type', 'status'], name='iftf_duover_operation_d4c254_idx'), models.Index(fields=['-created_at'], name='iftf_duover_created_8bda80_idx')],
            },
        ),
    ]

