# Generated by Django 5.2.11 on 2026-03-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iftf_duoverkoop', '0010_databaseoperation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='databaseoperation',
            new_name='iftf_duover_operati_1c1a1a_idx',
            old_name='iftf_duover_operation_d4c254_idx',
        ),
        migrations.RenameIndex(
            model_name='databaseoperation',
            new_name='iftf_duover_created_725d06_idx',
            old_name='iftf_duover_created_8bda80_idx',
        ),
    ]
