# Generated by Django 5.2.11 on 2026-03-19 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iftf_duoverkoop', '0011_rename_iftf_duover_operation_d4c254_idx_iftf_duover_operati_1c1a1a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='default', editable=False, max_length=20, unique=True)),
                ('subject_template', models.TextField(default='IFTF duo ticket confirmation - {{ verification_code }}', help_text='Template variables: {{ name }}, {{ verification_code }}, {{ performance1 }}, {{ performance2 }}, {{ purchase_date }}, {{ total_price }}.')),
                ('text_template', models.TextField(default='Hi {{ name }},\n\nYour duo ticket was registered successfully.\n\nTicket 1: {{ performance1 }}\nTicket 2: {{ performance2 }}\nOrder date: {{ purchase_date }}\nTotal paid: EUR {{ total_price }}\n\nVerification code: {{ verification_code }}\n\n{{ culture_card_line }}\nKeep this code available at the entrance.\n', help_text='Plain-text fallback body (Django template syntax).')),
                ('html_template', models.TextField(default='<!doctype html><html><body style="margin:0;padding:0;background:{{ background_color }};font-family:Arial,sans-serif;"><div style="max-width:{{ content_width }}px;margin:24px auto;background:{{ card_background_color }};border:1px solid {{ border_color }};border-radius:10px;overflow:hidden;"><div style="padding:16px 20px;background:{{ primary_color }};color:#fff;"><h2 style="margin:0;font-size:20px;">IFTF DuoVerkoop</h2></div><div style="padding:20px;color:#212529;line-height:1.5;"><p style="margin-top:0;">Hi <strong>{{ name }}</strong>, your duo ticket is confirmed.</p><p><strong>Ticket 1:</strong> {{ performance1 }}<br><strong>Ticket 2:</strong> {{ performance2 }}<br><strong>Order date:</strong> {{ purchase_date }}<br><strong>Total paid:</strong> EUR {{ total_price }}</p><p style="padding:12px 14px;background:#f8f9fa;border:1px solid {{ border_color }};border-radius:8px;"><strong>Verification code:</strong> <span style="color:{{ accent_color }};font-size:17px;">{{ verification_code }}</span></p>{% if culture_card_line %}<p style="margin:0 0 10px 0;">{{ culture_card_line }}</p>{% endif %}<p style="margin-bottom:0;">{{ footer_text }}</p></div></div></body></html>', help_text='HTML body (Django template syntax).')),
                ('primary_color', models.CharField(default='#0d6efd', max_length=7)),
                ('accent_color', models.CharField(default='#198754', max_length=7)),
                ('background_color', models.CharField(default='#f5f7fb', max_length=7)),
                ('card_background_color', models.CharField(default='#ffffff', max_length=7)),
                ('border_color', models.CharField(default='#dbe3ec', max_length=7)),
                ('content_width', models.PositiveIntegerField(default=640)),
                ('footer_text', models.CharField(default='See you at the IFTF performances.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Template Settings',
                'verbose_name_plural': 'Email Template Settings',
            },
        ),
    ]
