# Generated by Django 5.2.11 on 2026-03-19 16:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iftf_duoverkoop', '0017_alter_emailtemplatesettings_html_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplatesettings',
            name='html_template',
            field=models.TextField(default='<!doctype html><html><body style="margin:0;padding:0;background:{{ background_color }};font-family:Arial,sans-serif;"><div style="max-width:{{ content_width }}px;margin:24px auto;background:{{ card_background_color }};border:1px solid {{ border_color }};border-radius:10px;overflow:hidden;"><div style="padding:16px 20px;background:{{ primary_color }};color:#fff;display:flex;align-items:center;gap:16px;">{% if iftf_logo_url %}<img src="{{ iftf_logo_url }}" alt="IFTF" style="max-height:28px;max-width:28px;object-fit:contain;background:#fff;border-radius:4px;padding:2px;">{% endif %}<h2 style="margin:0;font-size:20px;">IFTF DuoVerkoop</h2></div><div style="padding:20px;color:#212529;line-height:1.5;"><p style="margin-top:0;">Hi <strong>{{ name }}</strong>, your duo ticket is confirmed.</p><p><strong>Ticket 1:</strong> {{ performance1 }}<br><strong>Ticket 2:</strong> {{ performance2 }}<br><strong>Order date:</strong> {{ purchase_date }}<br><strong>Total paid:</strong> EUR {{ total_price }}</p><p style="padding:12px 14px;background:#f8f9fa;border:1px solid {{ border_color }};border-radius:8px;"><strong>Verification code:</strong> <span style="color:{{ accent_color }};font-size:17px;">{{ verification_code }}</span></p>{% if culture_card_line %}<p style="margin:0 0 10px 0;">{{ culture_card_line }}</p>{% endif %}<div style="margin-top:16px;padding-top:12px;border-top:1px solid {{ border_color }};"><p style="margin:0 0 8px 0;"><strong>Important information</strong></p><ol style="margin:0 0 10px 20px;padding:0;"><li style="margin-bottom:6px;">This email only confirms your duo ticket sale. Practical details are shared by each association.</li><li style="margin-bottom:6px;">Information sent by the associations is the source of truth. Associations may send separate tickets through their own systems.</li><li style="margin-bottom:6px;">Keep your verification code easily accessible. It may be used at performance entrances, depending on association policy.</li><li style="margin-bottom:6px;">Report disputes or incorrect recipient information to <a href="https://iftf.be/contact/">https://iftf.be/contact/</a>.</li><li>More information: <a href="https://iftf.be">https://iftf.be</a></li></ol></div><p style="margin-bottom:0;">{{ footer_text }}</p></div></div></body></html>', help_text='HTML body (Django template syntax).'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=120)),
                ('house_number', models.CharField(max_length=10)),
                ('box', models.CharField(blank=True, default='', max_length=10)),
                ('postal_code', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(default='Belgium', max_length=40)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('street', 'house_number', 'box', 'postal_code', 'city', 'country'), name='unique_belgian_address')],
            },
        ),
        migrations.AddField(
            model_name='association',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iftf_duoverkoop.address'),
        ),
    ]
