"""
Django settings for iftf_duoverkoop project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

SECRET_KEY = os.environ.get("SECRET_KEY") or "django-insecure-CHANGE_ME"
# Default to False in hosted environments; set DEBUG=True explicitly for local dev.
DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/


ALLOWED_HOSTS = [
    "iftf-duoverkoop.onrender.com",
    "iftfduoverkoop.dpdns.org",
    "www.iftfduoverkoop.dpdns.org",
    "mg.iftfduoverkoop.dpdns.org",
    "localhost",
]
# Allow environment override/additions without losing defaults.
extra_hosts = [h.strip() for h in os.environ.get("ALLOWED_HOSTS", "").split(",") if h.strip()]
if extra_hosts:
    ALLOWED_HOSTS = sorted(set(ALLOWED_HOSTS + extra_hosts))


CSRF_TRUSTED_ORIGINS = [
    "https://iftf-duoverkoop.onrender.com",
    "https://iftfduoverkoop.dpdns.org",
    "https://www.iftfduoverkoop.dpdns.org",
    "https://mg.iftfduoverkoop.dpdns.org"
]



# Application definition

INSTALLED_APPS = [
    'iftf_duoverkoop.apps.IftfApp',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Block mutating app traffic while a database restore is active.
    'iftf_duoverkoop.src.core.middleware.RestoreMaintenanceLockMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Log request context for unhandled exceptions to Render stdout/stderr.
    'iftf_duoverkoop.src.core.middleware.RequestExceptionLoggingMiddleware',
]

ROOT_URLCONF = 'iftf_duoverkoop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'iftf_duoverkoop/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'iftf_duoverkoop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL')
DATABASES = {
    'default': dj_database_url.config(default=f'sqlite:///{BASE_DIR}/db.sqlite3', conn_max_age=600)
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'nl'

# Use an app-specific timezone env var to avoid accidental host defaults (for example UTC on PaaS).
TIME_ZONE = os.environ.get('DJANGO_TIME_ZONE', 'Europe/Brussels')

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / 'locale',
    BASE_DIR / 'iftf_duoverkoop/locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
STATICFILES_DIRS = [BASE_DIR / 'iftf_duoverkoop' / 'static']
STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = "/static/"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'iftf_duoverkoop' / 'media'
DATABASE_BACKUP_DIR = MEDIA_ROOT / 'backups'
DATABASE_BACKUP_MAX_UPLOAD_MB = int(os.environ.get('DATABASE_BACKUP_MAX_UPLOAD_MB', '300'))

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email settings (Mailgun HTTP API)
SEND_EMAILS = os.environ.get("SEND_EMAILS", "False").lower() == "true"
MAILGUN_API_KEY = os.environ.get("MAILGUN_API_KEY", "")
MAILGUN_DOMAIN = os.environ.get("MAILGUN_DOMAIN", "mg.iftfduoverkoop.dpdns.org")
MAILGUN_API_BASE_URL = os.environ.get("MAILGUN_API_BASE_URL", "https://api.eu.mailgun.net")
MAILGUN_FROM_EMAIL = os.environ.get("MAILGUN_FROM_EMAIL", "no-reply@mg.iftfduoverkoop.dpdns.org")
MAILGUN_FROM_NAME = os.environ.get("MAILGUN_FROM_NAME", "IFTF Duoverkoop")
MAIL_REQUEST_TIMEOUT = int(os.environ.get("MAIL_REQUEST_TIMEOUT", "15"))
IFTF_LOGO_URL = os.environ.get("IFTF_LOGO_URL", "/static/Site%20logo.png")

# Kept for compatibility with parts of Django that rely on DEFAULT_FROM_EMAIL.
DEFAULT_FROM_EMAIL = MAILGUN_FROM_EMAIL
SERVER_EMAIL = MAILGUN_FROM_EMAIL


STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Authentication settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/order/'
LOGOUT_REDIRECT_URL = '/login/'

# Session security settings
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG  # Use secure cookies in production
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 43200  # 12 hours
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = 'Lax'

# Security headers (production)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# Render-friendly logging: all key logs go to stdout so they appear in the Render console.
LOG_LEVEL = os.environ.get('LOG_LEVEL', 'INFO').upper()
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'iftf_duoverkoop': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        # Gunicorn's own Python logger (when run under gunicorn).
        'gunicorn.error': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}
